---
- project:
    check:
      jobs:
        - linters:
            nodeset: fedora-latest-pod
        - sf-ci-functional-external-elk: {}
        - sf-ci-functional-allinone: {}
        - sf-ci-upgrade-allinone: {}
    gate:
      jobs:
        - linters:
            nodeset: fedora-latest-pod
        - sf-ci-functional-external-elk: {}
        - sf-ci-functional-allinone: {}
        - sf-ci-upgrade-allinone: {}
