---
- name: Create required directory
  file:
    path: /etc/opensearch
    state: directory
    mode: '0755'
    owner: "{{ elk_uid }}"
    group: "{{ elk_gid }}"

- name: Configure Kibana
  template:
    src: opensearch_dashboards.yml.j2
    dest: "/etc/opensearch/opensearch_dashboards.yml"
    owner: "{{ elk_uid }}"
    group: "{{ elk_gid }}"
    mode: '0640'
  register: _kibana_conf
  no_log: True

- name: Restart service if necessary
  service:
    name: opensearch-dashboards
    state: restarted
    enabled: true
  ignore_errors: true
  when: _kibana_conf.changed
