---
- name: "Create index template"
  ansible.builtin.include_tasks: do-index-template.yaml
  loop:
    - "logstash-{{ user.tenant }}"
    - "zuul-{{ user.tenant }}"
    - "zuul.{{ user.real_tenant_name }}"
    - "performance-{{ user.tenant }}"
    - "subunit-{{ user.tenant }}"
    - "ftbfs-{{ user.tenant }}"
  loop_control:
    loop_var: index
