---
- name: Configure indexes
  template:
    src: indexer.conf.j2
    dest: /etc/logstash/conf.d/{{ item }}.conf
    mode: "0644"
    owner: "{{ logstash_uid }}"
    group: "{{ logstash_gid }}"

- name: Add crontab entry for pruning old indices
  cron:
    name: "Delete old logstash indexes for {{ item }}"
    state: absent
