---
- name: Configure indexes
  template:
    src: indexer.conf.j2
    dest: /etc/logstash/conf.d/{{ item }}.conf
    mode: "0644"
    owner: "{{ logstash_uid }}"
    group: "{{ logstash_gid }}"

- name: Add delete-indices file
  template:
    src: delete_old_indices.yml.j2
    dest: /etc/logstash/curator.d/delete_old_indices_{{ item }}.yml
    owner: "{{ curator_uid }}"
    group: "{{ curator_gid }}"

- name: Add curator configuration
  template:
    src: curator.yml.j2
    dest: /etc/logstash/curator.d/curator_{{ item }}.yml
    owner: "{{ curator_uid }}"
    group: "{{ curator_gid }}"
    mode: "0644"

- name: Add crontab entry for pruning old indices
  cron:
    name: "Delete old logstash indexes for {{ item }}"
    minute: "{{ 60 | random }}"
    hour: "{{ 24 | random }}"
    day: '*'
    job: >
      podman run
      --user 1000:1000
      -v /etc/logstash/curator.d/curator_{{ item }}.yml:/.curator/curator.yml:z
      -v /etc/logstash/curator.d/delete_old_indices_{{ item }}.yml:/curator/delete_old_indices_{{ item }}.yml:z
      -v /etc/opensearch/certs/localCA.pem:/etc/opensearch/certs/localCA.pem:z
      -it curator /curator/delete_old_indices_{{ item }}.yml
